// frontend-for-reference/src/components/PageHeader.vue
<script setup lang="ts">
import { useBreadcrumbs } from '@/composables/useBreadcrumbs'

const props = defineProps<{
  title: string
  description?: string
  icon?: string
  breadcrumbTitle?: string
  hideBreadcrumb?: boolean
}>()

const { breadcrumbs } = useBreadcrumbs(() => props.breadcrumbTitle)
</script>

<template>
  <div class="page-header mb-6">
    <v-breadcrumbs
      v-if="!hideBreadcrumb && breadcrumbs.length > 1"
      :items="breadcrumbs"
      density="compact"
      class="px-0 pt-0 pb-1"
    />
    <div class="d-flex align-center justify-space-between">
      <div class="d-flex align-center ga-2">
        <v-icon v-if="icon" :icon="icon" color="primary" size="26" />
        <h1 class="text-h5 font-weight-bold">{{ title }}</h1>
      </div>
      <div v-if="$slots.actions">
        <slot name="actions" />
      </div>
    </div>
    <p v-if="description" class="text-body-2 text-medium-emphasis mt-1 ml-1">{{ description }}</p>
    <slot name="description" />
    <v-divider class="mt-3" />
  </div>
</template>

// forend/src/components/PageHeader/index.tsx
import { Link } from 'react-router-dom';
import { useBreadcrumbs } from '../../hooks/useBreadcrumbs';

interface PageHeaderProps {
  title: string;
  description?: string;
  icon?: React.ReactNode;
  breadcrumbTitle?: string;
  hideBreadcrumb?: boolean;
  children?: React.ReactNode;
}

export default function PageHeader({
  title,
  description,
  icon,
  breadcrumbTitle,
  hideBreadcrumb = false,
  children,
}: PageHeaderProps) {
  const breadcrumbs = useBreadcrumbs(breadcrumbTitle);

  const showBreadcrumb = !hideBreadcrumb && breadcrumbs.length > 1;

  return (
    <div className="mb-6">
      {showBreadcrumb && (
        <nav className="flex items-center gap-1 px-0 pt-0 pb-1" aria-label="面包屑导航">
          {breadcrumbs.map((item, idx) => (
            <span key={idx} className="flex items-center gap-1">
              {idx > 0 && (
                <span style={{ color: 'var(--md-sys-color-on-surface-variant)' }} className="text-sm">
                  /
                </span>
              )}
              {item.path ? (
                <Link
                  to={item.path}
                  className="text-sm no-underline transition-colors"
                  style={{ color: 'var(--md-sys-color-primary)' }}
                >
                  {item.title}
                </Link>
              ) : (
                <span
                  className="text-sm"
                  style={{ color: 'var(--md-sys-color-on-surface)' }}
                >
                  {item.title}
                </span>
              )}
            </span>
          ))}
        </nav>
      )}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          {icon && (
            <span style={{ color: 'var(--md-sys-color-primary)' }} className="text-[26px]">
              {icon}
            </span>
          )}
          <h1 className="md-typescale-headline-small">{title}</h1>
        </div>
        {children && <div className="flex items-center gap-2">{children}</div>}
      </div>
      {description && (
        <p className="md-typescale-body-medium mt-1 ml-[34px]" style={{ color: 'var(--md-sys-color-on-surface-variant)' }}>
          {description}
        </p>
      )}
      <div
        className="mt-3"
        style={{ borderBottom: '1px solid var(--md-sys-color-outline-variant)' }}
      />
    </div>
  );
}
